/* object -> [what it is, what it is used for] */
const K={
"person":["A human being.","Detected so apps can count people, track activity or keep safety zones."],
"bicycle":["A two-wheeled, pedal-powered vehicle.","Cheap, eco-friendly travel, exercise and short deliveries."],
"car":["A four-wheeled motor vehicle.","Carrying people and goods on roads."],
"motorcycle":["A two-wheeled motor vehicle.","Fast personal travel and delivery."],
"airplane":["A powered, winged aircraft.","Long-distance passenger and cargo travel."],
"bus":["A large road vehicle.","Public transport for many passengers."],
"train":["Linked rail cars pulled by an engine.","Mass passenger and freight transport on rails."],
"truck":["A heavy motor vehicle.","Hauling cargo and construction material."],
"boat":["A small watercraft.","Travel, fishing and transport over water."],
"traffic light":["A signal with red, yellow and green lamps.","Controls vehicle and pedestrian flow at junctions."],
"fire hydrant":["A street water outlet.","Firefighters connect hoses to it to get water."],
"stop sign":["A red octagonal road sign.","Tells drivers to come to a full stop."],
"parking meter":["A coin or card-operated timer.","Collects fees for street parking."],
"bench":["A long seat for several people.","Resting in parks and public places."],
"bird":["A feathered, egg-laying animal.","Studied in nature; some are kept as pets or for food."],
"cat":["A small domestic pet.","Companionship and pest control."],
"dog":["A domesticated animal.","Companionship, security, herding and assistance."],
"horse":["A large hoofed animal.","Riding, sport and farm work."],
"sheep":["A wool-bearing farm animal.","Wool, meat and milk."],
"cow":["A large farm animal.","Milk, meat, leather and farm work."],
"elephant":["The largest land animal.","Wildlife conservation; historically used for heavy work."],
"bear":["A large furry mammal.","Wild animal; important to forest ecosystems."],
"zebra":["A striped African horse relative.","Wildlife; stripes help repel biting flies."],
"giraffe":["The tallest living animal.","Wildlife; eats leaves high in trees."],
"backpack":["A bag worn on both shoulders.","Carrying books, laptops and travel items."],
"umbrella":["A folding canopy on a handle.","Protection from rain and sun."],
"handbag":["A small bag carried by hand or strap.","Carrying wallet, phone and daily items."],
"tie":["A strip of cloth worn at the neck.","Formal and office wear."],
"suitcase":["A rigid or soft travel case.","Carrying clothes and belongings on trips."],
"frisbee":["A flying plastic disc.","Outdoor games and sport."],
"skis":["Long runners worn on the feet.","Gliding over snow."],
"snowboard":["A single board for snow.","Snow sport."],
"sports ball":["A ball for games.","Cricket, football, tennis and other sports."],
"kite":["A light frame flown on a string.","Recreation and festivals."],
"baseball bat":["A wooden or metal club.","Hitting the ball in baseball."],
"baseball glove":["A padded leather glove.","Catching the ball in baseball."],
"skateboard":["A small board on four wheels.","Sport and short-distance travel."],
"surfboard":["A buoyant board.","Riding ocean waves."],
"tennis racket":["A strung frame with a handle.","Hitting the ball in tennis."],
"bottle":["A narrow-necked container.","Storing and carrying water or drinks."],
"wine glass":["A stemmed drinking glass.","Serving wine."],
"cup":["A small open container.","Drinking tea, coffee or water."],
"fork":["A tool with prongs.","Picking up food while eating."],
"knife":["A blade with a handle.","Cutting food and materials. Handle with care."],
"spoon":["A bowl-shaped utensil.","Eating, stirring and serving."],
"bowl":["A deep round dish.","Serving soups, cereal and rice."],
"banana":["A yellow, curved fruit.","Quick energy and potassium."],
"apple":["A round fruit.","Eaten raw, juiced or cooked."],
"sandwich":["Fillings between bread slices.","A quick meal."],
"orange":["A citrus fruit.","Eaten fresh or juiced for vitamin C."],
"broccoli":["A green vegetable.","Cooked or eaten raw for fibre and vitamins."],
"carrot":["An orange root vegetable.","Salads, curries and juice."],
"hot dog":["A sausage in a bun.","Fast food."],
"pizza":["A baked flatbread with toppings.","A popular shared meal."],
"donut":["A ring-shaped fried dough.","A sweet snack."],
"cake":["A sweet baked dessert.","Celebrations and desserts."],
"chair":["A seat with a back.","Sitting at a desk, table or in a room."],
"couch":["A long, soft seat.","Relaxing in living rooms."],
"potted plant":["A plant grown in a pot.","Decoration and cleaner indoor air."],
"bed":["A furniture piece for sleeping.","Rest and sleep."],
"dining table":["A table for meals.","Eating, studying and gathering."],
"toilet":["A sanitation fixture.","Hygienic disposal of human waste."],
"tv":["A screen for video.","Watching shows, news and games."],
"laptop":["A portable computer.","Work, study, coding and entertainment."],
"mouse":["A handheld pointing device.","Moving the cursor on a computer."],
"remote":["A handheld controller.","Operating a TV or other device from a distance."],
"keyboard":["A set of keys for typing.","Entering text and commands."],
"cell phone":["A handheld mobile device.","Calls, messages, internet, camera and apps."],
"microwave":["An oven using microwaves.","Quickly heating and cooking food."],
"oven":["An enclosed heating appliance.","Baking and roasting."],
"toaster":["A small appliance with heating slots.","Browning bread."],
"sink":["A basin with a tap.","Washing hands and dishes."],
"refrigerator":["A cooling appliance.","Keeping food fresh and drinks cold."],
"book":["Bound pages of text.","Learning, reference and reading."],
"clock":["A time-keeping device.","Showing the time and setting schedules."],
"vase":["A decorative container.","Holding flowers."],
"scissors":["Two blades joined at a pivot.","Cutting paper, cloth and thread."],
"teddy bear":["A soft toy bear.","Play and comfort for children."],
"hair drier":["A heated air blower.","Drying and styling hair."],
"toothbrush":["A small brush on a handle.","Cleaning teeth and gums."]
};
